name: Get Cache Values
description: Gets values to pass to cache@v2 action to retrieve dependencies
inputs:
  hash:
    description: 'Hash of poetry.lock file'
    required: true
runs:
  using: composite
outputs:
  key:
    value: cache-${{ runner.os }}-${{ $(python -c 'import sys; print('-'.join(str(v) for v in sys.version_info))') }}-${{ inputs.hash }}
  path:
    value: |
      ${{ $(python -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])') }}
      .venv
