name: Dependencies
description: Installs pip, poetry and project dependencies lists in poetry.lock file
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install poetry
        python -m poetry config virtualenvs.in-project true
        python -m poetry install
