name: Develop

on:
  push:
    branches:
      - feature/*

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Develop Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Get cache values
        id: cache-values
        uses: ./.github/actions/cache-values
        with:
          hash: ${{ hashFiles('poetry.lock') }}

      - uses: actions/cache@v2
        id: cache
        with:
          key: ${{ steps.cache-values.outputs.key }}
          path: ${{ steps.cache-values.outputs.path }}

      - name: Install dependencies
        uses: ./.github/actions/dependencies

      - name: Run tests
        run: python -m poetry run pytest tests
