name: Develop

on:
  push:
    branches:
      - feature/*

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Develop Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Get cache values
        uses: ./.github/actions/cache-values
        id: cache-values

      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ${{ steps.cache-values.outputs.site-packages-path }}
            .venv
          key: ${{ steps.cache-values.outputs.cache-id }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install poetry
          python -m poetry config virtualenvs.in-project true
          python -m poetry install

      - name: Run tests
        run: python -m poetry run pytest tests
