name: Test

on:
  pull_request:
    branches:
      - develop
      - release
      - main
  push:
    branches:
      - develop
      - 'feature/*'

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Tests on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [Ubuntu, MacOS, Windows]
        python-version: [3.7, 3.8, 3.9]
        run-all:
          - ${{ contains(github.ref, 'release') || contains(github.ref, 'main') }}
        exclude:
          - run-all: false
            os: Ubuntu
            python-version: 3.7
          - run-all: false
            os: Ubuntu
            python-version: 3.8
          - run-all: false
            os: MacOS
          - run-all: false
            os: Windows
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get cache key and paths values
        id: cache-values
        uses: ./.github/actions/cache-values
        with:
          hash: ${{ hashFiles('poetry.lock') }}

      - uses: actions/cache@v2
        id: cache
        with:
          key: ${{ steps.cache-values.outputs.key }}
          path: ${{ steps.cache-values.outputs.paths }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        uses: ./.github/actions/dependencies

      - name: Run tests
        run: |
          source ~/.poetry/env
          poetry run pytest tests
